apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opendeepwiki
  namespace: mcp-servers
  labels:
    app.kubernetes.io/name: opendeepwiki
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: dev-cht-alb
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=QA
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:iam::720541322708:server-certificate/2026-q2-wildcard-dev-medicmobile-org-letsencrypt"  # ACM certificate ARN
spec:
  rules:
    - host: opendeepwiki.dev.medicmobile.org
      http:
        paths:
          - path: /api/mcp
            pathType: Prefix
            backend:
              service:
                name: opendeepwiki
                port:
                  number: 5085
